apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-path
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-path
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/jane-delivery/akuity-poc-config
          checkout:
          - branch: main
            path: ./src
      - uses: yaml-update
        config:
          path: ./src/dev/values.yaml
          updates:
          - key: poc.image.tag
            value: ${{ imageFrom("ghcr.io/jane-delivery/akuity-poc-app").Tag }}
      - uses: git-commit
        config:
          path: ./src
          message: "Update dev to new tag"
      - uses: git-push
        config:
          path: ./src
