poc:
  image:
    repository: "docker pull ghcr.io/jane-delivery/akuity-poc-app"
    tag: "v0.0.1"
  service:
    port: 80
    type: ClusterIP
  serviceAccount:
    create: false
  ingress:
    enabled: false
